# Generated by Django 3.2.18 on 2023-03-28 21:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='New deck', max_length=200)),
                ('language', models.TextField(choices=[('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Korean', 'Korean')], default='Chinese')),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_revised', models.DateTimeField(null=True)),
                ('color', models.TextField(default='#FFFFFF', validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', 'Color is not in hexadecimal format')])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.TextField(max_length=100)),
                ('characters', models.TextField(max_length=100)),
                ('status', models.TextField(choices=[('learnt', 'Learnt'), ('needs_revise', 'Revise'), ('not_known', 'Not Known')], default='not_known')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='flashcards_api.deck')),
            ],
        ),
    ]
