# Generated by Django 3.2.18 on 2023-03-26 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='New deck', max_length=200)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_revised', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.TextField(max_length=100)),
                ('characters', models.TextField(max_length=100)),
                ('pronounciation', models.TextField(max_length=100)),
                ('status', models.TextField(choices=[('learnt', 'Learnt'), ('needs revise', 'Revise'), ('not known', 'Not Known')], default='not known')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards_api.deck')),
            ],
        ),
    ]
