# Generated by Django 3.2.18 on 2023-03-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards_api', '0002_alter_deck_last_revised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='last_revised',
            field=models.DateTimeField(null=True),
        ),
    ]
