# Generated by Django 3.2.18 on 2023-03-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards_api', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.TextField(choices=[('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Korean', 'Korean')], default='Chinese'),
        ),
    ]
